CREATE TABLE public.accounts (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 owner_login VARCHAR(255) NOT NULL UNIQUE,
                                 balance NUMERIC(10, 2) NOT NULL DEFAULT 0,
                                 FOREIGN KEY (owner_login) REFERENCES public.users(login)
);