CREATE TABLE public.transaction_history (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            type VARCHAR(50) NOT NULL,
                                            amount NUMERIC(10, 2) NOT NULL,
                                            new_balance NUMERIC(10, 2) NOT NULL,
                                            account_id BIGINT NOT NULL,
                                            FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);
