CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          owner_login VARCHAR(255) NOT NULL UNIQUE,
                          balance DOUBLE NOT NULL DEFAULT 0
);
