CREATE TABLE transaction_history (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     type VARCHAR(50) NOT NULL,
                                     amount DOUBLE NOT NULL,
                                     new_balance DOUBLE NOT NULL,
                                     account_id BIGINT NOT NULL,
                                     FOREIGN KEY (account_id) REFERENCES accounts(id)
);
